baseURL: "https://itayelf.github.io/Maenalin/"
languageCode: "he-il"
languagedirection: rtl
title: "Maenalin"
enableGitInfo: true

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  expiryDate:
    - expiryDate
  lastmod:
    - :git
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date

redirects:
  - from: /**
    status: 404
    to: /404.html
